question_data = [
    {"type": "boolean", "difficulty": "easy", "category": "Science &amp; Nature",
     "question": "Upwelling in the ocean provides colder nutrient rich water for plants and decomposers.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science &amp; Nature",
     "question": "The Earth revolves around the Sun in one year.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"type": "boolean", "difficulty": "easy", "category": "Science &amp; Nature",
                                       "question": "An Astronomical Unit is the distance between Earth and the Moon.",
                                       "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science &amp; Nature",
     "question": "Not including false teeth; A human has two sets of teeth in their lifetime.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science &amp; Nature",
     "question": "Salt is 100% composed of Sodium.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science &amp; Nature",
     "question": "Celiac Disease is a disease that effects the heart, causing those effected to be unable to eat meat.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science &amp; Nature",
     "question": "An atom contains a nucleus.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science &amp; Nature",
     "question": "Psychology is the science of behavior and mind.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"type": "boolean", "difficulty": "easy", "category": "Science &amp; Nature",
                                       "question": "Igneous rocks are formed by excessive heat and pressure.",
                                       "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science &amp; Nature",
     "question": "A plant that has a life cycle for more than a year is known as an annual.", "correct_answer": "False",
     "incorrect_answers": ["True"]}]
